# This determines the platform paths needed for Maven artifacts
if(MSVC)
    set(platform windows)
    string(FIND ${CMAKE_CXX_COMPILER} arm64 is_arm64)
    if(NOT is_arm64 EQUAL -1)
        set(arch arm64)
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
        set(arch x86-64)
    else()
        set(arch x86)
    endif()
elseif(APPLE)
    set(platform osx)
    set(arch universal)
elseif(LINUX)
    set(platform linux)
    if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
        set(arch x86-64)
    elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
        set(arch arm64)
    elseif(SOFTFP)
        set(arch athena)
    else()
        set(arch arm32)
    endif()
endif()
